# Generated by Django 6.0.1 on 2026-01-10 15:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('planted_date', models.DateField()),
                ('expected_harvest_date', models.DateField()),
                ('area', models.FloatField(help_text='Area in hectares')),
                ('notes', models.TextField(blank=True, null=True)),
                ('farmer', models.ForeignKey(limit_choices_to={'role': 'farmer'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CropActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('planting', 'Planting'), ('watering', 'Watering'), ('fertilizing', 'Fertilizing'), ('harvesting', 'Harvesting'), ('pest_control', 'Pest Control'), ('other', 'Other')], max_length=20)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True, null=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='farms.crop')),
            ],
        ),
    ]
