# Generated by Django 6.0.1 on 2026-01-12 12:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='area',
            field=models.FloatField(blank=True, help_text='Area in hectares', null=True),
        ),
        migrations.AlterField(
            model_name='crop',
            name='expected_harvest_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crop',
            name='planted_date',
            field=models.DateField(default=datetime.date(2026, 1, 12)),
        ),
    ]
