# Generated by Django 6.0.1 on 2026-01-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0002_alter_crop_area_alter_crop_expected_harvest_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropactivity',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('overdue', 'Overdue')], default='pending', max_length=10),
        ),
    ]
