# Generated by Django 6.0.1 on 2026-01-13 15:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0004_animal_animalactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='variety',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='crop',
            name='planted_date',
            field=models.DateField(default=datetime.date(2026, 1, 13)),
        ),
    ]
