# Generated by Django 6.0.1 on 2026-01-21 16:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0005_crop_variety_alter_crop_planted_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='planted_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
